version: 2

project_name: tasia

before:
  hooks:
    - go mod tidy

builds:
  - id: tasia
    main: ./cmd/tasia
    binary: tasia
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/dzh01/tasia/internal/cli.Version={{ .Version }}
      - -X github.com/dzh01/tasia/internal/cli.Commit={{ .ShortCommit }}
      - -X github.com/dzh01/tasia/internal/cli.Date={{ .Date }}

archives:
  - id: tasia
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

release:
  github:
    owner: dzh01
    name: tasia
  draft: false
  prerelease: auto
  mode: replace

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
